### ISSUE TITLE
Blender Issue

### ISSUE THREAD

**Issue by JaylenTang** [fudan-generative-vision/champ#100]
Hi there!

Thanks for uploading smooth smpl!
It seems that I ran into some issues when I was using blender.

When I ran:
blender --background --python scripts/data_processors/smpl/smooth_smpls.py --smpls_group_path driving_videos/your_video_1/smpl_results/smpls_group.npz --smoothed_result_path driving_videos/your_video_1/smpl_results/smpls_group.npz

I got:
![image](https://github.com/fudan-generative-vision/champ/assets/111931401/4b4be4ce-d628-4142-8c45-7cc713e14ab3)

And When I ran:
blender scripts/data_processors/smpl/blend/smpl_rendering.blend --background --python scripts/data_processors/smpl/render_condition_maps.py --driving_path transferd_result/smpl_results --reference_path reference_imgs/images/0001.png

I just got:

![image](https://github.com/fudan-generative-vision/champ/assets/111931401/7e68d525-eb50-4b2a-81ea-1b037c7f753a)

Thanks a lot.

Best regard.

**Comment by Leoooo333** [comment]
Hi there, as mentioned in our document, you should install Blender 3.x Version from [here](https://download.blender.org/release/Blender3.6/). Hope it helps.

**Comment by JaylenTang** [comment]
> Hi there, as mentioned in our document, you should install Blender 3.x Version from [here](https://download.blender.org/release/Blender3.6/). Hope it helps.

Thank you for your useful advice.  Now it works well.

**Comment by linjing7** [comment]
@JaylenTang Hi, how did you solve it? I install Blender 3.6 and there still exists the error similar to yours.

**Comment by JaylenTang** [comment]
> @JaylenTang Hi, how did you solve it? I install Blender 3.6 and there still exists the error similar to yours.

Hi there, if you are using linux system, after install Blender 3.6, you can try: 

export PATH=/home/yubai03/aJialin_Tang/champ00/blender-3.6.0-linux-x64:$PATH

This can help you set path for your newly installed blender 3.6.0

Hope this helps.

**Comment by linjing7** [comment]
It works now. Thanks for your kind reply!

**Comment by yankainan** [comment]
> > @JaylenTang Hi, how did you solve it? I install Blender 3.6 and there still exists the error similar to yours.
> 
> Hi there @linjing7 , if you are using linux system, after installing Blender 3.6, you can try:
> 
> export PATH=/home/yubai03/aJialin_Tang/champ00/blender-3.6.0-linux-x64:$PATH
> 
> This can help you set path for your newly installed blender 3.6.0
> 
> Hope this helps.

I install Blender 3.6 then export aas u said but there still exists the error similar to yours.
