### ISSUE TITLE
Questions about smpl_rendering.blend

### ISSUE THREAD

**Issue by TianQi-777** [fudan-generative-vision/champ#102]
Thank you for your sharing.

I want to know how [smpl_rendering.blend](https://github.com/fudan-generative-vision/champ/blob/master/scripts/data_processors/smpl/blend/smpl_rendering.blend) is obtained. I ran [render_condition_maps.py](https://github.com/fudan-generative-vision/champ/blob/master/scripts/data_processors/smpl/render_condition_maps.py) and found that the depth map and mask map are blender's built-in codes (The implementation for extracting depth map and mask map is not clearly defined in the [render_condition_maps.py](https://github.com/fudan-generative-vision/champ/blob/master/scripts/data_processors/smpl/render_condition_maps.py), and only two output paths are provided. i.e., [Depth Output](https://github.com/fudan-generative-vision/champ/blob/b205392e54160de2cdc2ebd7b9832970317704a0/scripts/data_processors/smpl/render_condition_maps.py#L187) and [Mask Output](https://github.com/fudan-generative-vision/champ/blob/b205392e54160de2cdc2ebd7b9832970317704a0/scripts/data_processors/smpl/render_condition_maps.py#L193)). What should I do if I want to edit and customize the content in [smpl_rendering.blend](https://github.com/fudan-generative-vision/champ/blob/master/scripts/data_processors/smpl/blend/smpl_rendering.blend)? Is there any corresponding instructions or tutorial links? 

Looking forward to your reply :)

**Comment by jiangzhengkai** [comment]
Same problems.

**Comment by Leoooo333** [comment]
Hi there. The [smpl_rendering.blend](https://github.com/fudan-generative-vision/champ/blob/master/scripts/data_processors/smpl/blend/smpl_rendering.blend) is a blender file with necessary rendering settings inside. Actually I uses different blender nodes to build up Physically Based Rending with Cycle Engine inside the Blender file. You can open it in Blender GUI and modify them. I would suggest for basic knowledge in `Blender Material Node` and `Blender Composite Node` if you like.

1. Actually the `Normal` and `Semantic` could be found as Materials in Blender shading. `Normal` here is physically corrected in Cycle  Engine. The `Semantic` map is rendering with vertex color shader.
![image](https://github.com/fudan-generative-vision/champ/assets/72211694/be1d6939-37ba-4e21-85f8-d5bf7d97aed6)

2. Open Blender compositing to find the `depth` and `mask`  and `visualized_imgs`. Blender will render RGB and Alpha and Depth within one pass. So I move the `depth` and `mask` into Blender compositor. Mask is just a alpha channel stored in gray scale. Depth here is normalized to [0,1]. You can customize the composite node in Blender GUI. 
![image](https://github.com/fudan-generative-vision/champ/assets/72211694/f122199c-9d07-447e-88ac-45a94ee9d3b3)

**Comment by TianQi-777** [comment]
Thanks for your quick reply and sharing :)
