### ISSUE TITLE
basicModel_neutral_lbs_10_207_0_v1.0.0.pkl

### ISSUE THREAD

**Issue by AndrewFBrown** [fudan-generative-vision/champ#113]
Where can I find this file? I can't find this file anywhere.

**Comment by AricGamma** [comment]
refer to https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md#download-models.
In the 4th step of `Download models` section

**Comment by AndrewFBrown** [comment]
I've checked the website but I failed to find this version.

**Comment by AndrewFBrown** [comment]
> refer to https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md#download-models. In the 4th step of `Download models` section

<img width="842" alt="b5b1cd101e6fa4141e0a1155f1244bc1" src="https://github.com/fudan-generative-vision/champ/assets/55049078/3fdf7c29-c146-4a5d-983a-3bef5e30903b">

May I know which one I should download here?

**Comment by RuijieH** [comment]
Hi, May I know how do you solve this question? I just find "basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl"

**Comment by bichunyang419** [comment]
So how solve this question?
