### ISSUE TITLE
Organization of training data per the README causes errors

### ISSUE THREAD

**Issue by pearbender** [fudan-generative-vision/champ#119]
I have organized my training data per the README and scanning it causes errors. I fixed it but I don't know whether the README or the code is wrong

```
/training_data/
|-- video01/          # A video data frame
|   |-- depth/        # Depth frame sequance
|   |-- dwpose/       # Dwpose frame sequance
|   |-- mask/         # Mask frame sequance
|   |-- normal/       # Normal map frame sequance
|   `-- semantic_map/ # Semanic map frame sequance
|-- video02/
|   |-- ...
|   `-- ...
`-- videoN/
|-- ...
`-- ...
```

![image](https://github.com/fudan-generative-vision/champ/assets/140408754/3f831c9a-e605-431e-a559-bef2f95d803c)

**Comment by CodeConductor520** [comment]
Excuse me, do you know where the problem is now? Have you solved this problem?

**Comment by pearbender** [comment]
Yes, the code I posted in the screenshot solves this problem.

**Comment by CodeConductor520** [comment]
Thank you for your answer. Also, may I ask if your training was successful? How was the training result.

**Comment by pearbender** [comment]
I haven't completed training yet. I will post the results as soon as I am successful rendering anime characters at higher quality.

**Comment by CodeConductor520** [comment]
I am still waiting for the results of your training. Have there been any new developments recently？

**Comment by pearbender** [comment]
Sorry. I gave up on training because it was estimated to take approximately 1800 hours. I discovered by reading the paper that training requires 8 A100 NVIDIA tensor core GPUs.

**Comment by AricGamma** [comment]
Closing this issue. If any questions, please open a new one. Thank you for your attention.
