### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by JaylenTang** [fudan-generative-vision/champ#120]
![image](https://github.com/fudan-generative-vision/champ/assets/111931401/fafa932c-8193-47fa-87e4-8fb91aaf7b86)
![image](https://github.com/fudan-generative-vision/champ/assets/111931401/2f752175-7abd-4756-9844-01b8336382ed)

Hi, may I know how much memory it takes for training? my batch size is 1, and I am using 3090Ti with one Gpu 24GB

**Comment by pearbender** [comment]
See https://github.com/fudan-generative-vision/champ/issues/115

**Comment by AricGamma** [comment]
Closing this issue. If you have further questions, reopen it.
