### ISSUE TITLE
when   i  test   my video, i have error  

### ISSUE THREAD

**Issue by zhanghongyong123456** [fudan-generative-vision/champ#121]
when  i   run Render SMPL via Blender
blender scripts/data_processors/smpl/blend/smpl_rendering.blend --background --python scripts/data_processors/smpl/render_condition_maps.py --driving_path transferd_result/smpl_results --reference_path reference_imgs/images/your_ref_img_A.png

i have this  error:
 File "G:\blender-3.6.0-windows-x64\3.6\scripts\modules\bpy\__init__.py", line 20, in <module>
    from _bpy import (
    from _bpy import (
ModuleNotFoundError: No module named '_bpy'
ModuleNotFoundError: No module named '_bpy'

![image](https://github.com/fudan-generative-vision/champ/assets/48466610/859e5c82-b2ec-4d0d-a5c8-5dfab62ff70b)
![image](https://github.com/fudan-generative-vision/champ/assets/48466610/28251bd8-b489-4eeb-a058-f8d80dcbed45)

**Comment by pearbender** [comment]
I had this error. I have a fix for it.

**Comment by zhanghongyong123456** [comment]
> See this PR: #118
It's OK,Thanks
