### ISSUE TITLE
Strong image distortion 

### ISSUE THREAD

**Issue by deepbeepmeep** [fudan-generative-vision/champ#13]
Hi

Thank you very much for your great work. 

I have tried your model using reference images of my own and the end result is often not visually pleasing at all (face distorted, image proportions changed, ...). 

I would be grateful if you could provide any potential constraint regarding the source image, for instance :  
- any ratio height / width for the image 
- proportion of the head versus the rest of the image 
- location of the head and body in the image (horizontally centered ?)
- amount of body visible and the pose of the body 
- max dimensions of the image

Many thanks in advance

**Comment by ShenhaoZhu** [comment]
Hi, thank you for your attention. We are currently working on the Parametric Shape Alignment section. The documentation and scripts for this part will be released soon. For now, if you want to try your own reference image, we recommend choosing a reference image that aligns as closely as possible with the guidance motion sequence.

**Comment by AricGamma** [comment]
Please refer to #61 .
If any questions, please open a issue.
