### ISSUE TITLE
reference image

### ISSUE THREAD

**Issue by yankainan** [fudan-generative-vision/champ#132]
Thank you for your excellent work!
I would like to ask, what is your strategy for selecting a reference image from a video clip? For example, do you select the first frame of a video clip?

**Comment by AricGamma** [comment]
Which step are you dealing with?

**Comment by wanghaisheng** [comment]
`-- ref_images/ # Reference image samples(Optional)
why @AricGamma this is optional, can you explain a little how to get and metric of this reference image

**Comment by yankainan** [comment]
> Which step are you dealing with?

that isn't in data_process.md, just a strategy of selecting reference images

**Comment by AricGamma** [comment]
> > Which step are you dealing with?
> 
> that isn't in data_process.md, just a strategy of selecting reference images

Or what do you want to do with the selected reference image? Training? Inference? Or sth. else?

**Comment by AricGamma** [comment]
> `-- ref_images/ # Reference image samples(Optional) why @AricGamma this is optional, can you explain a little how to get and metric of this reference image

ref_images folder is optional logically. But we coupled video SMPL and ref images preprocessing together. You can ignore the `Optional` annotation for now. We will optimize the data processing logic.

**Comment by wanghaisheng** [comment]
@AricGamma  how to gen such ref_images does this have some minimal requirements
