### ISSUE TITLE
how can I get "--reference_path reference_imgs/smpl_results/your_ref_img_A.npy"?

### ISSUE THREAD

**Issue by goshiaoki** [fudan-generative-vision/champ#133]
Thank you for your great work. The result is interesting. I have two questions.

I'm trying running the following code, but I'm not sure about how to get the "your_ref_img_A.npy". Could you give me advice to get that?
> python -m scripts.data_processors.smpl.smpl_transfer --reference_path reference_imgs/smpl_results/your_ref_img_A.npy --driving_path driving_videos/your_video_1 --output_folder transferd_result --figure_transfer --view_transfer

Also, I'm not sure about "reference_imgs" directory. I would appreciate it if you would answer these questions.

<img width="843" alt="Screenshot 2024-06-06 at 8 07 49 PM" src="https://github.com/fudan-generative-vision/champ/assets/45219415/7f4e176f-48e3-4696-8fe1-18e736df3d1e">

**Comment by WasabiCode** [comment]
Hey! 

I have the similar issue

**Comment by AricGamma** [comment]
You can find a "reference_img.npy" from the outputs of the second step "generate_smpls".
Refer to https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md#produce-motion-data

**Comment by AricGamma** [comment]
Closing this issue. If any questions, please open a new one.

**Comment by SizheAn** [comment]
Hi @AricGamma 

I'm still wondering what `reference_imgs` means? From the training example, we have 800 videos. So `driving_videos` contain all the images of these videos. What about `reference_imgs`? I don't see them in the rawdata folder from https://huggingface.co/datasets/fudan-generative-ai/champ_trainning_sample/tree/main

Thanks!
