### ISSUE TITLE
render_condition_map sometimes has errors

### ISSUE THREAD

**Issue by notorious-eric** [fudan-generative-vision/champ#136]
Hi, thank you for your work, when I use render_condition_map for rendering, sometimes the code stops midway because some file error from `os.rename(os.path.join(render_path, "depth", f"{0:04d}.png"), depth_path)` (depth, normal xxx all possible). I checked and found sometimes 0000.png does not exist, but somehow the `if os.path.isfile(os.path.join(render_path, "depth", f"{0:04d}.png")):` checks yes. I wonder if you have encountered the problem? I guessed it is about multi-processing but not sure

**Comment by jx-zhong-for-academic-purpose** [comment]
I encountered the same problem. What was the reason and how could we solve it?
