### ISSUE TITLE
How to install Blender in the environment 'champ'

### ISSUE THREAD

**Issue by Beijia11** [fudan-generative-vision/champ#137]
I have tried to download blender,but when I run the 'blender scripts/data_processors/smpl/blend/smpl_rendering.blend --background --python scripts/data_processors/smpl/render_condition_maps.py ' ,it may show this error.
blender: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

**Comment by AricGamma** [comment]
Maybe you can get answer in this issue from blender repo.
https://projects.blender.org/blender/blender/issues/59769

**Comment by AricGamma** [comment]
Closing this issue. If any further questions, please reopen it.
