### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by KenwayZY** [fudan-generative-vision/champ#139]
Warning, your free project has been used by others to make money, in this link and you will know what happened!!

https://replicate.com/camenduru/champ/api/learn-more

**Comment by AricGamma** [comment]
Thank you. 😁
This project uses the MIT open source protocol. Developers are welcome to make some attempts without violating the open source agreement.

**Comment by AricGamma** [comment]
Closing this issue. Thank you for your support.
