### ISSUE TITLE
How could you get the results of Animate Anyone?

### ISSUE THREAD

**Issue by WuHuadong3** [fudan-generative-vision/champ#14]

**Comment by kyrie111** [comment]
maybe from qianwen app？

**Comment by ShenhaoZhu** [comment]
Due to the lack of an official open-source implementation, we get the results from an unofficial implementation: [Moore-AnimateAnyone](https://github.com/MooreThreads/Moore-AnimateAnyone) as noted in paper.

**Comment by notorious-eric** [comment]
Hi, what about Magic-Animate code? they do not release training code either.

**Comment by ShenhaoZhu** [comment]
@notorious-eric We did not use their training code, we only use their official code and checkpoints for inference.

**Comment by notorious-eric** [comment]
I get it, thank you.
