### ISSUE TITLE
Question about inference code

### ISSUE THREAD

**Issue by kevinu0628** [fudan-generative-vision/champ#153]
I use my own reference images, but encountering a problem as follow.
Traceback (most recent call last):
  File "/home/champ/inference.py", line 321, in <module>
    main(cfg)
  File "/home/champ/inference.py", line 299, in main
    grid_video = torch.cat([ref_video_tensor, result_video_tensor], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 4 but got size 3 for tensor number 1 in the list.

**Comment by YuGuilliman** [comment]
@kevinu0628 Hi, I encountered the same problem, how do you solve it?

**Comment by lhx-max** [comment]
how to solve it, same with me
