### ISSUE TITLE
Please put your models on huggingface - Google drive quota already exceeded

### ISSUE THREAD

**Issue by SoftologyPro** [fudan-generative-vision/champ#16]

**Comment by kyrie111** [comment]
https://huggingface.co/camenduru

**Comment by SoftologyPro** [comment]
Any mirrors for the example data?
https://drive.google.com/file/d/1-sJlnnZu-nTNTvRtvFVr_y-2_CA5-_Yz/view

**Comment by ShenhaoZhu** [comment]
Thank you for your advice, we put models and example data on HuggingFace and update the download links in README.
