### ISSUE TITLE
Finetune on costom dataset

### ISSUE THREAD

**Issue by Haodong-Yan** [fudan-generative-vision/champ#163]
Thanks for opensource such great work. But I found the result on some full body dataset is not good enough, relatively speaking. I want to try fine-tune the stage 2 using some full body pose dataset like zjumocap, snapshot and etc. But I found when I loaded your weight and trained I found the validation result is like noise  
![image](https://github.com/user-attachments/assets/d6fa5287-aa76-4065-9486-034151bacfb9)
I am pretty sure I load all your weight first. And it is weird when I didn't load motion_module, the result seems ok. 
![image](https://github.com/user-attachments/assets/2196d3ad-d5d9-4b2f-8db9-43a0c24243b1)

**Comment by NinoNeumann** [comment]
This is indeed strange. If you haven't changed the network structure, I recommend checking if there is an issue with the motion module weights being corrupted. It might be a good idea to re-download the motion module.

**Comment by Haodong-Yan** [comment]
> This is indeed strange. If you haven't changed the network structure, I recommend checking if there is an issue with the motion module weights being corrupted. It might be a good idea to re-download the motion module.

It seems I changed the frames number. If I keep the original frame number, it becomes normal
