### ISSUE TITLE
给项目点赞！制作 Motion 的这一套流程技术太强了！

### ISSUE THREAD

**Issue by wikeeyang** [fudan-generative-vision/champ#17]
✌✌✌用了最少帧的 06 样本，跑起来了。。。
启动中，请耐心等待......
03/26/2024 15:38:35 - INFO - root - Running inference ...
03/26/2024 15:38:39 - INFO - models.unet_3d - loaded temporal unet's pretrained weights from pretrained_models\stable-diffusion-v1-5\unet ...
03/26/2024 15:38:46 - INFO - models.unet_3d - Load motion module params from pretrained_models\champ\motion_module.pth
D:\AITest\Champ\runtime\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
03/26/2024 15:38:49 - INFO - models.unet_3d - Loaded 453.20928M-parameter motion module
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
 90%|████████████████████████████████████████████████████████████████████████        | 18/20 [18:10<02:01, 60.65s/it]

**Comment by ShenhaoZhu** [comment]
Thank you for your interest in our work. We are still working to improve Champ. Please stay tuned for our follow-up work, thank you☺️ .

**Comment by cklogic** [comment]
怎么制作样本数据呢？
