### ISSUE TITLE
How to get depth images

### ISSUE THREAD

**Issue by adf1178** [fudan-generative-vision/champ#18]
Wonderful Work!!
I really appreciate you release your model and testing code. I have a question about the depth images. How do you get them?
Thank you!

**Comment by ShenhaoZhu** [comment]
Hi, adf1178. We export the SMPL model to Blender and render it into depth images, we will later provide the instructions and scripts for this. For now, you can also try some monocular depth predictors like [Depth-Anything](https://github.com/LiheYoung/Depth-Anything).

**Comment by adf1178** [comment]
Thanks for your quick reply! I will try depth-anything and SMPL.
