### ISSUE TITLE
Commercial usage?

### ISSUE THREAD

**Issue by jadechip** [fudan-generative-vision/champ#20]
Are the checkpoints available for commercial usage?
Thank you for your work!

**Comment by ShenhaoZhu** [comment]
This project aims to serve the developer community and follows the open-source guidelines of Apache 2.0. Commercial applications related to this project should also adhere to these guidelines. We will continue to provide open-source implementations of training and data-related services to benefit developers at large.

**Comment by jadechip** [comment]
Thank you for your response and your contributions!
