### ISSUE TITLE
CUDA out of memory, feature request

### ISSUE THREAD

**Issue by nitinmukesh** [fudan-generative-vision/champ#21]
This looks really wonderful. Many thanks for sharing with the community.
I gave up looking at the System requirement and Graphics card requirement but thought no harm in trying.

So I tested on Windows 11 + RTX 4060 8 GB VRAM + 16 GB RAM and it worked.
The changes I did was to keep the frames inside motion to 20 frames and deleted remaining from all folders within motion. [EDIT] Tried with 40 motion frames and it worked without complaining. :)

1. requesting to add a feature of batch processing and the number of frames can be specified in configs/inference.yaml
2. Correct the system requirements to also include Windows. along with Ubuntu20.04

Here is the output
https://github.com/fudan-generative-vision/champ/assets/2102186/b3fc3b93-a5cc-4ef7-94d3-22cd4e5ed9f3

**Comment by G-force78** [comment]
Batch process would be good we can then lower the batch to run on less VRAM, slower but functional. LCM and lightning use enabled too.

**Comment by Leeway213** [comment]
For Windows, you can refer to  #38 .
and we got the feature request of optimize memory cost. This will be in our program.

**Comment by nitinmukesh** [comment]
> For Windows, you can refer to #38 . and we got the feature request of optimize memory cost. This will be in our program.

Thank you for the update, this can be closed as memory optimization is in your Roadmap.
Appreciate your efforts to create this awesome tool.
