### ISSUE TITLE
operating system

### ISSUE THREAD

**Issue by Mahanandha10** [fudan-generative-vision/champ#26]
how to run on windows or mac os

**Comment by ShenhaoZhu** [comment]
We have not implemented a version for Windows or MacOS. Thanks to the contributions of other users, you can try some alternative versions, such as [champ-for-windows](https://github.com/sdbds/champ-for-windows).

**Comment by nitinmukesh** [comment]
@Mahanandha10 

Refer this video for Windows installation
https://youtu.be/XasrlKbFKy0?si=ptbExNRocdYVWGnJ

**Comment by Leeway213** [comment]
Refer to [#38 ](url)

**Comment by Leeway213** [comment]
Refer to #38
