### ISSUE TITLE
Blender script for animations

### ISSUE THREAD

**Issue by al3dv2** [fudan-generative-vision/champ#3]
Hi, your script is awesome! I have a question, when will you make the Blender file available for generating new animations from video? Because at the moment, I can only use the example data for animation

**Comment by Leoooo333** [comment]
Thanks! Cause there are many scripts on the rendering side, we are working on it to make it easy and robust for all users. Don't worry, we will publish all of that within this week👏.

**Comment by chojinie** [comment]
@Leoooo333 I'm so anticipated to release. Thanks!

**Comment by sam598** [comment]
@Leoooo333 I would recommend even releasing the base mesh/skeleton renderer as a Blender file. There will be a lot of people who want to create novel animations from scratch, not necessarily convert 2D video to a 3D skeleton.

**Comment by nitinmukesh** [comment]
Hello @Leoooo333 

Please any updates on releasing the process of creating all maps withing motion folder.

I know you guys have been working hard for this and this is open source project. But you have done something really good and we can't wait to use it. Thank you

**Comment by lxd941213** [comment]
> Hi there, thanks for your patience! I just released SMPL & Rendering code. Check the README for details!

Where are the codes you mentioned? Why haven't I seen anything

**Comment by HaiyiMei** [comment]
I wanna share our repo of synthetic data rendering [XRFeitoria](https://github.com/openxrlab/xrfeitoria). With this Python package, you can render RGB and annotations through Blender using the system Python. Check out the sample code for rendering motion of amass [here](https://github.com/openxrlab/xrfeitoria/blob/main/samples/blender/07_amass.py).

**Comment by Leoooo333** [comment]
Hi @lxd941213 sorry that this repo has been deleted cause it's not convenient for users to set up the environment. You can git clone the previous tested version @ https://github.com/Leoooo333/champ, they are the same. Also, there are several checkpoint URLs in 4D-Humans that could not be directly visited from China, you may need to configure VPN to avoid files missing errors.

**Comment by Leoooo333** [comment]
Thanks @HaiyiMei! It's a great toolbox. Now I set Normal, Semantic Map as materials in a blender file, can it be directly reused in XRFeitoria?

**Comment by HaiyiMei** [comment]
> Thanks @HaiyiMei! It's a great toolbox. Now I set Normal, Semantic Map as materials in a blender file, can it be directly reused in XRFeitoria?

Yeah, I think you can. Check this out:

```python
import xrfeitoria as xf
from xrfeitoria.data_structure.models import RenderPass


xf_runner = xf.init_blender(cleanup=False, project_path='/path/to/your/blend_file')
seq = xf_runner.sequence(seq_name='render', level='Scene')
mesh = xf_runner.Actor('{actor_name}')  # This is to find an object called `actor_name` in your blend file, or you can import from fbx file, or from `smplx_addon`

# create new material
mat = xf_runner.Material.new(mat_name=f'Material')
diffuse_tex_path = '/path/to/tex_path'
mat.add_diffuse_texture(diffuse_tex_path, 'diffuse')

# or just use existing material
mat = xf_runner.Material('{material_name'})

# set material to mesh
mesh.set_material(mat)

# render
camera = xf_runner.Camera('camera')  # use a camera called `camera` predefined in your blend file, or you can create a new one
seq.use_camera(camera)
seq.add_to_renderer(
    output_path='output_path',  # enter your output_path
    render_passes=[RenderPass('img', 'png')],
    resolution=[512, 512],
)
xf_runner.render()
```

**Comment by Leoooo333** [comment]
Hi all, we have released the SMPL & Rending code. Git clone the updated Champ and have a try!

**Comment by AricGamma** [comment]
Closing this issue. If any further questions, please reopen or create a new one.
