### ISSUE TITLE
How to obtain normal map

### ISSUE THREAD

**Issue by adf1178** [fudan-generative-vision/champ#31]
According to your previous advice, I have tried Smpler-X and depth anything to obtain 3-D human body and corresponding depth image. I also have a question about how to obtain normal map. Could you please tell me the model you use?

Thank you!

**Comment by tommy-qichang** [comment]
Maybe you could try the normal map model used in the ControlNet?
https://github.com/lllyasviel/ControlNet?tab=readme-ov-file
https://huggingface.co/lllyasviel/ControlNet

**Comment by adf1178** [comment]
> Maybe you could try the normal map model used in the ControlNet? https://github.com/lllyasviel/ControlNet?tab=readme-ov-file https://huggingface.co/lllyasviel/ControlNet

Thanks for your suggestion! I have tried the model of controlnet, but I find that the results are not the same as the examples in the paper. The background of the results obtained by normalbae model is not clean, maybe bring some noise.

**Comment by Leoooo333** [comment]
Hi @adf1178 , in the paper we use SMPL only. The normal map could be found as material in the Blender file `smpl_rendering.blend`. The Rendering code is also released so you can run on blender for all the conditions' maps.

**Comment by AricGamma** [comment]
Refer to #61 . If any questions, please reopen issues.
