### ISSUE TITLE
What model is to be used for extraction of the semantic segmentation map?

### ISSUE THREAD

**Issue by LEES0196** [fudan-generative-vision/champ#33]
Thank you for your awesome work released in open source! I really appreciate the impact this paper and code will bring to the community.

I would like to test this model by using in-the-wild video which requires preprocessing.
I am planning to use the follows:

- Depth: Depth Anything with greyscale
- Dwpose: official dwpose repository
- Normal: ICON normal map
- mask: unsure whether it is necessary as "inference.yaml" does not require mask for its guidance_types by default

Meanwhile, I am unsure what models I should be using for semantic segmentation map. Please guide me if there is any model that are suitable to be used in the data preprocessing stage.

**Comment by LEES0196** [comment]
Also I assume there will be an error for example guide video 7, 8 and 9.
   -> it has additional video file "output.mp4" (outpuo.mp4 for video 7)
This goes into "inference.py" and causes an error at line 78 since it is not an image

The error message after replacing the absolute directory using ~ is:

```
  File “~/miniconda3/envs/champ/lib/python3.10/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file ‘~/champ/example_data/motions/motion-08/normal/output.mp4'
```

I assume adding the following lines after line 73 would work?
```
try: Image.open(guidance_image_path).convert("RGB")
except: continue
```

**Comment by wooj0216** [comment]
Hello, I am trying to get the normal map for my custom data with ICON.
May I ask you to share the code for obtaining normal map from the data?

**Comment by LEES0196** [comment]
If you mean the official github repo, here's the link. https://github.com/YuliangXiu/ICON
I would recommend using DSINE instead if you want easier inference here https://github.com/baegwangbin/DSINE
Best wishes :)

**Comment by wooj0216** [comment]
> If you mean the official github repo, here's the link. https://github.com/YuliangXiu/ICON I would recommend using DSINE instead if you want easier inference here https://github.com/baegwangbin/DSINE Best wishes :)

Thank you for replying! I will try it :)
