### ISSUE TITLE
2 Issues regarding example data

### ISSUE THREAD

**Issue by LEES0196** [fudan-generative-vision/champ#35]
1. In example_data/motions/motion-0X:
There are extra output.mp4 which should not be in the dataset.
This causes an error in 'inference.py' line 78 by opening a video file using PIL.Image module
I fixed this in my local by adding the following lines after line 73:
`
try: Image.open(guidance_image_path).convert("RGB")
except: continue
`

2. In example_data/motions/motion-07:
There is an extra 0389_all.png for motion-07/semantic_map while other depth, dwpose, mask, normal does not have 0389_all.png
This causes an assertion error in 'inference.py' line 87 
I manually fixed it by erasing the file in my folder, but it would be grateful if you fix it by adding a code that automatically skips the image if it does not match with other guidances.

**Comment by ShenhaoZhu** [comment]
Thank you for your careful observation. I will check it and correct the errors in the example data.
