### ISSUE TITLE
怎么制作motion数据？

### ISSUE THREAD

**Issue by cklogic** [fudan-generative-vision/champ#39]
包括：depth dwpose mask normal semantic_map

**Comment by Leoooo333** [comment]
Hi, we have released SMPL & Rendering Code. Check README for details.

**Comment by min-star** [comment]
@Leoooo333 hello, where is the released SMPL & Rendering Code?It seems to be canceled!

**Comment by min-star** [comment]
@Leoooo333 hello, where is the released SMPL & Rendering Code?It seems to be canceled!

**Comment by ChengBinJin** [comment]
@Leoooo333 
Data pre-processing codes are canceled?

**Comment by Leoooo333** [comment]
Hi sorry that this repo has been deleted cause it's not convenient for users to set up the environment. You can git clone the previous tested version @ https://github.com/Leoooo333/champ, they are the same. Also, there are several checkpoint URLs in 4D-Humans that could not be directly visited from China, you may need to configure VPN to avoid files missing errors.

**Comment by shengyuting** [comment]
@Leoooo333 Thank you for great work. I have tryed the data pre-processing code and acquired an output video. It looks a bit shaky. So, I want to konw how to smooth. Thank you !!!

https://github.com/fudan-generative-vision/champ/assets/22219297/e874fbe5-c85b-4238-a3a8-441e3c3e45e6

**Comment by Leoooo333** [comment]
Hi all, We have released the SMPL & Rending code. Git clone the updated Champ and have a try!

**Comment by AricGamma** [comment]
Refer to #61 .
