### ISSUE TITLE
Vram required?

### ISSUE THREAD

**Issue by toyxyz** [fudan-generative-vision/champ#4]
Thanks for the great work! What is the minimum Vram required?

**Comment by ShenhaoZhu** [comment]
Hi toyxyz, inferring a video of 250 frames requires approximately 20GB of GPU memory. If you encounter an issue with insufficient GPU memory, consider reducing the length of the guidance motion sequence.

**Comment by ShenhaoZhu** [comment]
@sdbds 
Hi, the default motion-01 in `inference.yaml` has more than 500 frames. Maybe you could try switching to other set of example data with less frames.

**Comment by sdbds** [comment]
> @sdbds Hi, the default motion-01 in `inference.yaml` has more than 500 frames. Maybe you could try switching to other set of example data with less frames.

Thank u, it works.
