### ISSUE TITLE
[swscaler @ 0x68f11c0] Warning: data is not aligned! This can lead to a speed loss

### ISSUE THREAD

**Issue by oceanogeology** [fudan-generative-vision/champ#42]
测试数据如何与指定motion对齐

**Comment by Leoooo333** [comment]
Hi there, we will release our SMPL & Rendering code for that. You can follow the instruction `Transfer SMPL`  on Readme.md.

**Comment by AricGamma** [comment]
Closing this issue. If any futher questions, please reopen.
