### ISSUE TITLE
can't open file 'C:\\sd1\\champ\\inference_smpl.py'

### ISSUE THREAD

**Issue by nitinmukesh** [fudan-generative-vision/champ#49]
Hello,

I am trying to SMPL & Rendering for own video.

Followed all the steps but it comes up with an error

```
(venv) C:\sd1\champ>python inference_smpl.py  --reference_imgs_folder test_smpl/reference_imgs --driving_videos_folder test_smpl/driving_videos --device 1
C:\Program Files\Python310\python.exe: can't open file 'C:\\sd1\\champ\\inference_smpl.py': [Errno 2] No such file or directory
```

Can't locate this file on github

**Comment by LEES0196** [comment]
inference_smpl.py is located at "/4D-Humans" folder which you need to git clone separately
try 
`git clone https://github.com/fudan-generative-vision/4D-Humans.git`

**Comment by zhou-linpeng** [comment]
where is the 4D-humans git, I cant find it, can you share it with us, thanks!

> inference_smpl.py is located at "/4D-Humans" folder which you need to git clone separately try `git clone https://github.com/fudan-generative-vision/4D-Humans.git`, move to 4D-Humans, do the environmental setup then run inference_smpl.py

where is the 4D-humans git, I cant find it, can you share it with us, thanks!

**Comment by nitinmukesh** [comment]
> where is the 4D-humans git, I cant find it, can you share it with us, thanks!
> 
> > inference_smpl.py is located at "/4D-Humans" folder which you need to git clone separately try `git clone https://github.com/fudan-generative-vision/4D-Humans.git`, move to 4D-Humans, do the environmental setup then run inference_smpl.py
> 
> where is the 4D-humans git, I cant find it, can you share it with us, thanks!

You need to use this in Command prompt / Shell
Paste the folowing and press enter. It will clone the repository
git clone https://github.com/fudan-generative-vision/4D-Humans.git

**Comment by Leoooo333** [comment]
Hi @zhou-linpeng sorry that this repo has been deleted cause it's not convenient for users to set up the environment. You can git clone https://github.com/Leoooo333/4D-Humans, they are the same. Also, there are several checkpoint URLs in 4D-Humans that could not be directly visited from China, you may need to configure VPN to avoid files missing errors.

**Comment by zhou-linpeng** [comment]
> Hi @zhou-linpeng sorry that this repo has been deleted cause it's not convenient for users to set up the environment. You can git clone https://github.com/Leoooo333/4D-Humans, they are the same. Also, there are several checkpoint URLs in 4D-Humans that could not be directly visited from China, you may need to configure VPN to avoid files missing errors.

got it, thanks!

**Comment by zhou-linpeng** [comment]
> Hi @zhou-linpeng sorry that this repo has been deleted cause it's not convenient for users to set up the environment. You can git clone https://github.com/Leoooo333/4D-Humans, they are the same. Also, there are several checkpoint URLs in 4D-Humans that could not be directly visited from China, you may need to configure VPN to avoid files missing errors.

when I run the last step, I got this error:
`Blender 3.2.0 (hash e05e1e369187 built 2022-06-08 10:37:43)
/run/user/0/gvfs/ non-existent directory
Python path configuration:
  PYTHONHOME = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin'
  PYTHONPATH = './'
  program name = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/blender'
  isolated = 0
  environment = 1
  user site = 0
  import site = 1
  sys._base_executable = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin/python3.10'
  sys.base_prefix = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin'
  sys.base_exec_prefix = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin'
  sys.platlibdir = 'lib'
  sys.executable = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin/python3.10'
  sys.prefix = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin'
  sys.exec_prefix = '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin'
  sys.path = [
    './',
    '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin/lib/python310.zip',
    '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin/lib/python3.10',
    '/dataset/users/zlp/4D-Humans/blender-3.2.0-linux-x64/3.2/python/bin/lib/python3.10/lib-dynload',
  ]
Internal error initializing Python!
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f9b94478140 (most recent call first):
  <no Python frame>`

**Comment by Leoooo333** [comment]
Hi @zhou-linpeng We have released the SMPL & Rending code. Git clone the updated Champ and have a try!

**Comment by AricGamma** [comment]
Please refer to #61.
If any questions, reopen issues please.
