### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by Syndulla** [fudan-generative-vision/champ#5]
Hello,

This looks like an excellent piece of work - thank you for releasing openly with models available!

Question on whether there are any means by which we can reduce VRAM usage? For those of us who don't have an A100 :)

Cheers.

**Comment by ShenhaoZhu** [comment]
Hi Syndulla, inferring a video of 250 frames requires approximately 20GB of GPU memory. If you encounter an issue with VRAM, consider reducing the length of the guidance motion sequence.

**Comment by Syndulla** [comment]
Thank you - I will give that a go!
