### ISSUE TITLE
Have new schedule about the dataset and training code release?

### ISSUE THREAD

**Issue by glennchina** [fudan-generative-vision/champ#54]
Hi,buddy.Thank you very much for your great work and I am very appreciate.
As you notice the roadmap will delay.
I am very concerned your new schedule.

**Comment by Leeway213** [comment]
We are dealing with some code specification problems strictly. Sorry about that.
SMPL Rendering code will release in one or two days, thank you for your attention and we'll speed up up up 🚀🚀🚀🚀🚀🚀

**Comment by subazinga** [comment]
Thanks for your patient attention! We are very sorry about the code releasing delay... We are now trying to revise the code for better readability and easier to use.

**Comment by nitinmukesh** [comment]
> Thanks for your patient attention! We are very sorry about the code releasing delay... We are now trying to revise the code for better readability and easier to use.

You don't have to be sorry. You guys did an awersome work. Thank you.

**Comment by glennchina** [comment]
> We are dealing with some code specification problems strictly. Sorry about that. SMPL Rendering code will release in one or two days, thank you for your attention and we'll speed up up up 🚀🚀🚀🚀🚀🚀

Thanks very much for your reply.I think your project will be the TOP of HumanMotion field,better than Alibaba's AnimateAnyone.

As you mentioned in your paper 4.1 
`The dataset is segmented as follows:Bilibili (2540 videos), Kuaishou (920 videos), Tiktok & Youtube (1438 videos),and Xiaohongshu (430 videos).`
Will you share the dataset(videos or urls)?

**Comment by Leoooo333** [comment]
@glennchina Yeah we have a plan to release it. If you require immediate use, please contact us via [email](mailto://siyuzhu@fudan.edu.cn) for more information.

**Comment by Jie-zju** [comment]
> > @glennchina Yeah we have a plan to release it. If you require immediate use, please contact us via [email](mailto://siyuzhu@fudan.edu.cn) for more information.
> 
> Thanks a lot.I'll send an email right now.

@glennchina Hello! Have you got training dataset ? Please share url with me! Thanks a lot!

**Comment by glennchina** [comment]
> > > @glennchina Yeah we have a plan to release it. If you require immediate use, please contact us via [email](mailto://siyuzhu@fudan.edu.cn) for more information.
> > 
> > 
> > Thanks a lot.I'll send an email right now.
> 
> @glennchina Hello! Have you got training dataset ? Please share url with me! Thanks a lot!

Sorry,I haven't get their any training dataset,they just reply:will release later

**Comment by glennchina** [comment]
@AricGamma So when will you release the traing dataset?For now,you just release some samples.
Thanks

**Comment by subazinga** [comment]
Guys, sorry for forgetting to reply...
We have released the dataset on 2024/05/05, please refer to the news in Readme or just click this [link](https://huggingface.co/datasets/fudan-generative-ai/champ_trainning_sample)

Please continue to follow the news in ReadMe for the latest updates.

**Comment by glennchina** [comment]
> Guys, sorry for forgetting to reply... We have released the dataset on 2024/05/05, please refer to the news in Readme or just click this [link](https://huggingface.co/datasets/fudan-generative-ai/champ_trainning_sample)
> 
> Please continue to follow the news in ReadMe for the latest updates.

Thanks very much.

> > > @glennchina Yeah we have a plan to release it. If you require immediate use, please contact us via [email](mailto://siyuzhu@fudan.edu.cn) for more information.
> > 
> > 
> > Thanks a lot.I'll send an email right now.
> 
> @glennchina Hello! Have you got training dataset ? Please share url with me! Thanks a lot!
Here is the dataset.Thanks FuDan team
https://huggingface.co/datasets/fudan-generative-ai/champ_trainning_sample

**Comment by AricGamma** [comment]
closing this issue. If any questions, please open a new one.

**Comment by manhtoanbui01** [comment]
Thank you for your great work.
According to your paper, 5 000 videos were used to train the model, but the link you provided contains only 832 videos. Could you provide access to the remaining dataset?
