### ISSUE TITLE
i can not find the file "smpl_rendering.blend"

### ISSUE THREAD

**Issue by PCcp0110** [fudan-generative-vision/champ#59]
hello, 
thank you for your great work, it is solid and meaningful. 
i am interested in your four conditions(depth, normal, seg_map, pose) rendered from SMPL model. this is also meaning for my work now.
however, i follow your old version code(https://github.com/Leoooo333/champ/tree/master?tab=readme-ov-file). when i process SMPL section, i have finished Fit SMPL and Transfer SMPL successfully. 
THE QUESTION is the command "**blender smpl_rendering.blend --background --python rendering.py --driving_path test_smpl/transfer_result/smpl_results --reference_path test_smpl/reference_imgs/images/ref.png**" of RINDERING section, i can not find the file **smpl_rendering.blend** in the code.
i am confused, how can i find this file to finish my rendering? thank you!

**Comment by Leoooo333** [comment]
Hi @PCcp0110 It's under my [fork of 4D-Humans](https://github.com/Leoooo333/4D-Humans/tree/6670f0bf0d9a433ad72d5a175f74e7e6822c1bce) root directory. Also, I have an updated version of PR under review now. It's user-friendly now, which you could find it in this branch: https://github.com/Leoooo333/champ/tree/feature/data_process

**Comment by PCcp0110** [comment]
well, thank you for your replying, i will try again.

> Hi @PCcp0110 It's under my [fork of 4D-Humans](https://github.com/Leoooo333/4D-Humans/tree/6670f0bf0d9a433ad72d5a175f74e7e6822c1bce) root directory. Also, I have an updated version of PR under review now. It's user-friendly now, which you could find it in this branch: https://github.com/Leoooo333/champ/tree/feature/data_process

**Comment by AricGamma** [comment]
Please refer to #61.
If any questions, reopen issue please.
