### ISSUE TITLE
The resulting video flickers badly

### ISSUE THREAD

**Issue by 762572251** [fudan-generative-vision/champ#60]
Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?

https://github.com/fudan-generative-vision/champ/assets/67625350/2e9530fc-46aa-4d32-bcfb-0d69a75ac562

**Comment by zhou-linpeng** [comment]
> Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> 
>  grid_wguidance.mp4

Hi~,  How do you render with dwpose condiftion? i find the orignal script render with depth、mask、normal、semantic map, without dwpose condition。

**Comment by 762572251** [comment]
> > Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> > grid_wguidance.mp4
> 
> Hi~, How do you render with dwpose condition? i find the orignal script render with depth、mask、normal、semantic map, without dwpose condition。

I git the original version released by the author at the beginning, and there is inference_dwpose.py in the original version.

**Comment by zhou-linpeng** [comment]
> > > Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> > > grid_wguidance.mp4
> > 
> > 
> > Hi~, How do you render with dwpose condition? i find the orignal script render with depth、mask、normal、semantic map, without dwpose condition。
> 
> I git the original version released by the author at the beginning, and there is inference_dwpose.py in the original version.

Did you aligned the conditions with your input image, it's seems they aren't aligned well

**Comment by 762572251** [comment]
> > > > Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> > > > grid_wguidance.mp4
> > > 
> > > 
> > > Hi~, How do you render with dwpose condition? i find the orignal script render with depth、mask、normal、semantic map, without dwpose condition。
> > 
> > 
> > I git the original version released by the author at the beginning, and there is inference_dwpose.py in the original version.
> 
> Did you aligned the conditions with your input image, it's seems that they aren't aligned well

Yes, I've aligned them

**Comment by Leoooo333** [comment]
Hi @762572251, the jittering could be solved by `SMPL Smooth`, which is based on Blender. It will be released ASAP. Would you mind to send me the `smpls_group.npz` of your driving video? I can smooth it for you right now.

**Comment by zhou-linpeng** [comment]
> Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> 
>  grid_wguidance.mp4

here is my result, but there is also some artrifact indeed 

https://github.com/fudan-generative-vision/champ/assets/147801386/9cf7cec9-f6a4-4421-a134-d9795b3dbc6f

**Comment by Leoooo333** [comment]
@zhou-linpeng Thanks for this example. It seems a good result(as diffusion model) with only several artifacts in background. We will keep going and release better Champ in the next version. Stay tuned!

**Comment by subazinga** [comment]
Hi, there. I found you have solved the problem mentioned in the title. So I'll close this issue. If you have any other concern, we can open a new issue to discuss. Thanks!

**Comment by guozhongluo** [comment]
@Leoooo333 Could you send me the SMPL Smooth code? My email is 472338311@qq.com

**Comment by guozhongluo** [comment]
> > > > > Thank you for your work! I have followed your instructions to complete the entire process, but the generated video flickers very seriously. Is this caused by SMPL not being smoothed? Can this problem be perfectly solved if SMPL is smoothed?
> > > > > grid_wguidance.mp4
> > > > 
> > > > 
> > > > Hi~, How do you render with dwpose condition? i find the orignal script render with depth、mask、normal、semantic map, without dwpose condition。
> > > 
> > > 
> > > I git the original version released by the author at the beginning, and there is inference_dwpose.py in the original version.
> > 
> > 
> > Did you aligned the conditions with your input image, it's seems that they aren't aligned well
> 
> Yes, I've aligned them

How did you achieve the smooth motion in driving the video, without any jitter? Is it done with SMPL smooth?
