### ISSUE TITLE
some problems in data_process.md

### ISSUE THREAD

**Issue by ZZfive** [fudan-generative-vision/champ#66]
When i follow data_process.md to setup environment and download models, i realize some problems about downloading models. The original text said "download our Pose model dw-ll_ucoco_384.onnx and Det model yolox_l.onnx, then put them into Champ/annotator/ckpts/", the "Champ" is the root directory of the project or "pretrained_models/champ",or should the models be placed in an unopened "annotator/ckpts"?

As shown in the red boxes in the screenshots below, "annotator" and "hmr2" don’t feel like third-party libraries, but there is no relevant directories in repo. Has it not been released yet? 
![image](https://github.com/fudan-generative-vision/champ/assets/57706634/6e3d915d-9931-4764-9f2e-c8d9005a445d)

![image](https://github.com/fudan-generative-vision/champ/assets/57706634/fc9b2309-8074-4662-97fc-b2fb80997165)

**Comment by AricGamma** [comment]
Yes, "Champ" means the root directory of the project.

For hmr2 and DWPose dependencies, you can just follow "Install dependencies" section in data_process.md.

**Comment by ZZfive** [comment]
> Yes, "Champ" means the root directory of the project.
> 
> For hmr2 and DWPose dependencies, you can just follow "Install dependencies" section in data_process.md.

Sorry, this is my problem. Because of the network environment, I could only install it offline, so I did not use "pip+git" in the working directory. The above problem occurred without detailed analysis of the project structure. Thanks for your quick reply!!!
