### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:    - gxx=12   - gcc=12

### ISSUE THREAD

**Issue by mikeyimer** [fudan-generative-vision/champ#68]
![a](https://github.com/fudan-generative-vision/champ/assets/137673481/dc0246d0-8283-4477-b90e-4e1bd514c7d0)

**Comment by JPW0080** [comment]
The requested packages are for an Linux environment.

**Comment by AricGamma** [comment]
Hi, on Windows, there is no need to perform this step. You need a `Microsoft C++ build tools` v14.0 or greater instead.

**Comment by AricGamma** [comment]
We are trying to supplement docs about how to run on Windows. Hope you guys to help to improve this.

**Comment by nitinmukesh** [comment]
> We are trying to supplement docs about how to run on Windows. Hope you guys to help to improve this.

I already did a youtube tutorial for Windows. Still works fine.
No need of poetry, conda, etc or any complex setup
