### ISSUE TITLE
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

### ISSUE THREAD

**Issue by mikeyimer** [fudan-generative-vision/champ#70]
![a1](https://github.com/fudan-generative-vision/champ/assets/137673481/c145e74f-630b-4270-8dc6-2b234ef4dd41)

**Comment by AricGamma** [comment]
We haven't passed all test cases on Windows, this will be ready soon.
You can try to add this line temporarily under `hmr2` import lines:
```python
if os.name == "nt":
    os.environ.pop("PYOPENGL_PLATFORM")
```

**Comment by K-Rjw** [comment]
你好，请问你是如何解决这个问题的，我使用  
if os.name == "nt":
    os.environ.pop("PYOPENGL_PLATFORM") 
    ，但问题依然没有解决
