### ISSUE TITLE
the code of computing PSNR in the Disco repository is wrong

### ISSUE THREAD

**Issue by Delicious-Bitter-Melon** [fudan-generative-vision/champ#8]
The Disco code of computing PSNR as follows is wrong:
https://github.com/Wangt-CN/DisCo/blob/8538889c9ee9edd8dd43ffee182d1a91ce7a9828/tool/metrics/ssim_l1_lpips_psnr.py#L13.

![image](https://github.com/fudan-generative-vision/champ/assets/48432038/e7f41152-c08b-4f1d-8b96-5ce8d8edb491)

As pointed out in https://github.com/Wangt-CN/DisCo/issues/86, the accurate code is mse = np.mean((original/1.0 - compressed/1.0) ** 2) instead of mse = np.mean((original - compressed) ** 2) , because original and compressed images are uint8 in their code, and (original - compressed) * * 2 will cause numerical overflow.

**If you use their evaluation code of computing PSNR, please update your results.**

**Comment by Delicious-Bitter-Melon** [comment]
**The wrong version will improve PSNR.** For example, 
![image](https://github.com/Boese0601/MagicDance/assets/48432038/11e139eb-b596-4e19-ae90-15af36cf0ab9)

**Comment by ShenhaoZhu** [comment]
Thank you for the reminder. To ensure a fair comparison, we follow the method for calculating PSNR that was used by Disco and subsequent works.

**Comment by Delicious-Bitter-Melon** [comment]
> Thank you for the reminder. To ensure a fair comparison, we follow the method for calculating PSNR that was used by Disco and subsequent works.

In some cases, the wrong computation manner will increase PSNR but in some cases it decreases PSNR. Are you sure that your conclusion in your paper will not change after using the correct PSNR calculation method?

![image](https://github.com/fudan-generative-vision/champ/assets/48432038/12edfafe-9019-404d-86cb-0c4a66082bb8)

**Comment by Delicious-Bitter-Melon** [comment]
Besides, I am certain that the FID calculation method used by Disco is correct, but I am not sure if other metrics such as FVD are correct.
