### ISSUE TITLE
smooth smpl

### ISSUE THREAD

**Issue by guozhongluo** [fudan-generative-vision/champ#80]
Has anyone reproduced the smooth SMPL code? I'd like to discuss it.

**Comment by jitsm** [comment]
Also curious about this. My motions are very jumpy

**Comment by sonodaatom** [comment]
When using characters with large faces, I would also like to know how to solve the issue where the face becomes small like a human's, even when using the view_transfer option for alignment.

**Comment by Leoooo333** [comment]
Hi @guozhongluo We have released the blender smooth scripts. Update and try on it.

**Comment by AricGamma** [comment]
Closing this issue. if any further questions, please reopen it or create a new one.
