### ISSUE TITLE
How does this job perform on animal character?

### ISSUE THREAD

**Issue by guwen007** [fudan-generative-vision/champ#81]
Hi, this is an excellent job. But I found that applying videos to animals dancing can cause facial problems. Is it right?

**Comment by siyuzhu-fudan** [comment]
Thank you for your interest in this work. This work cannot be directly applied to animal character, given the strong constraints of human geometry and motion.

**Comment by siyuzhu-fudan** [comment]
We will consider this advice in the later project.
