### ISSUE TITLE
SemanticMap

### ISSUE THREAD

**Issue by Carlyx** [fudan-generative-vision/champ#82]
Awesome Work!

I find the background color of Semantic Map in your paper (Purple) is different with the one generated with your script (Black).
Will this affect the results?

**Comment by ShenhaoZhu** [comment]
The origin background color is purple due to built-in algorithm in Blender. In our experiments, we found that a purple background can be mistaken as part of the body in some cases, so we add black ground to semantic map in all our experiments, including the results in our paper.

**Comment by Carlyx** [comment]
Okay, Thanks for your reply!
