### ISSUE TITLE
SMPL Transfer

### ISSUE THREAD

**Issue by ougan** [fudan-generative-vision/champ#84]
I tried transferring the smpl parameters on my video, 
but I don't want to change the camera parameters (--view_transfer was not stored), the blender results are wrong.

The result of depth map is as shown in the figure
<img width="462" alt="企业微信截图_166d779e-0815-468a-bc85-fd32dc977991" src="https://github.com/fudan-generative-vision/champ/assets/25608204/6f7cadf3-6c27-406d-811d-9e8289f974da">

**Comment by Leoooo333** [comment]
Thanks @ougan for pointing out the bug. I have fixed it, it's on PR reviewing now.

**Comment by AricGamma** [comment]
Closing this issue. If any further questions, please create a new one.
