### ISSUE TITLE
attention map visulization

### ISSUE THREAD

**Issue by Wangxuefeng92** [fudan-generative-vision/champ#86]
hi，sir
thanks for your greate work on champ! I am interesting about ‘how to get the attention maps of depth,normal,semantic as mentioned in in Fig.3 in your paper ’. could you share the method/code ?

**Comment by code-conquer** [comment]
+1

**Comment by AricGamma** [comment]
Please refer to https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md
