### ISSUE TITLE
When will you release a hugging face demo ,THANK YOU IN ADVANCE ♡♡♡

### ISSUE THREAD

**Issue by Sarthak-999** [fudan-generative-vision/champ#87]

**Comment by Inferencer** [comment]
they have one on replicate while you wait
https://replicate.com/camenduru/champ

**Comment by nitinmukesh** [comment]
@zhou-linpeng 
Awesome. How did you got smooth animation? Please post quick guide (steps).

**Comment by sonodaatom** [comment]
Great work!
I would also like to know how you make the video smooth without flickering!

**Comment by Leoooo333** [comment]
Hi @nitinmukesh @sonodaatom, the Blender smooth script is released. Update and Check the [doc](https://github.com/fudan-generative-vision/champ/blob/master/docs/data_process.md).

**Comment by sonodaatom** [comment]
@Leoooo333 
Thank you for your great work and reply!

I would also appreciate an answer to the bug that is not generated when using figure_transfer.
https://github.com/fudan-generative-vision/champ/issues/84

Also, like --view_transfer, I would like the balance of the body to be aligned with the reference image, but to be moved when the video is moved from back to front, do you have any idea how to handle such a request?

**Comment by Leoooo333** [comment]
Hi @sonodaatom, so now `cam_t`, which is the global location of the SMPL, is fixed as Reference when using view-transfer. To transfer with moving locations, I recommend to edit this line.
https://github.com/fudan-generative-vision/champ/blob/b205392e54160de2cdc2ebd7b9832970317704a0/scripts/data_processors/smpl/smpl_transfer.py#L111

For a very simple example, you can translate the mean of your motion sequence's `cam_t` to reference's. Here's the persudo code.
```python
motion_loc_mean = result_dict_list["camera"].mean()
ref_loc = reference_dict["cam_t"] 
rescale_loc_list = result_dict_list["camera"] - (motion_loc_mean - ref_loc)
rescale_loc_list *= ref_loc / motion_loc_mean  # simple perspective transform

for i in range() :
    result_dict["cam_t"] = rescale_loc_list [i]
```

**Comment by sonodaatom** [comment]
@Leoooo333 
Thank you for the pseudo code.
I will try it.

**Comment by AricGamma** [comment]
Closing this issue. If any questions, please open a new one.
