### ISSUE TITLE
SMPL & Rendering Error

### ISSUE THREAD

**Issue by moo1o** [fudan-generative-vision/champ#88]
The following error occurred during SMPL & Rendering.
Tested in a Linux Docker container environment.
Could you help me? please.
<img width="739" alt="image" src="https://github.com/fudan-generative-vision/champ/assets/26794490/f26c35e3-ca4d-4f62-9627-351de7e56eb6">

**Comment by AricGamma** [comment]
Try this if using Ubuntu
```shell
apt-get install libglfw3-dev libgles2-mesa-dev
```
