### ISSUE TITLE
invalid device id

### ISSUE THREAD

**Issue by moo1o** [fudan-generative-vision/champ#89]
I'm fitting SMPL. 
An error called invalid device ID occurred.
Thank you for your help.
<img width="847" alt="image" src="https://github.com/fudan-generative-vision/champ/assets/26794490/a3a00411-6b38-4f36-92a3-870f2752e2b8">

**Comment by wyyfffff** [comment]
I also met this problem :(

**Comment by AricGamma** [comment]
Maybe pyrender cannot find the right GPU device. Try to specify the `EGL_DEVICE_ID`. Refer to https://github.com/mmatl/pyrender/pull/60

**Comment by moo1o** [comment]
@AricGamma 
I am testing by changing the EGL_DEVICE_ID according to your advice. But none of the device ids are valid. Am I getting the gpu device id wrong? When checking the device ID, I tested it by entering the values confirmed through the lspci command and the nvidia-smi command.
<img width="735" alt="image" src="https://github.com/fudan-generative-vision/champ/assets/26794490/408d1433-5e3f-4861-a8c4-5a8ad005f302">
<img width="550" alt="image" src="https://github.com/fudan-generative-vision/champ/assets/26794490/7a6947c5-46ac-480e-a99f-733269447c1d">

**Comment by moo1o** [comment]
It appears that the devices array received through query_devices() in the get_device_by_index() function of egl.py is output as an empty array as []. Is this also a related issue?

**Comment by AricGamma** [comment]
I'm not sure about that.😕😕 Maybe you could open an issue in pyrender project

**Comment by moo1o** [comment]
Taking a hint from the pyrender project page, I succeeded by replacing EGL with omesa. thank you

**Comment by kelu007** [comment]
> I succeeded by replacing EGL with omesa. thank you

Could you please share how to replace EGL with omesa?

**Comment by moo1o** [comment]
Please refer to the contents of this page.
https://github.com/HongwenZhang/PyMAF/issues/79
