### ISSUE TITLE
About the release of training code and dataset

### ISSUE THREAD

**Issue by syorami** [fudan-generative-vision/champ#98]
Thanks for your great work and sharing. I've noticed that the training code and dataset would be published after Apr 20 listed in your roadmap. Is there any problem causing the delay? Could I access the related resources in advance?

**Comment by Leoooo333** [comment]
Hi @syorami the training code is under review in PR. For the training datasets, refer  #54

**Comment by AricGamma** [comment]
Refer to #107

**Comment by syorami** [comment]
> Hi @syorami the training code is under review in PR. For the training datasets, refer #54

hey @Leoooo333 it seems that partial dataset has been released. Is there any schedule to release the whole dataset?
